using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace blackjack
{
    /// <summary>
    /// aRandomVariable has its own intermediate class to
    /// make sure dice "patten" stays consistent among a class
    /// </summary>
    public class aRandomVariable
    {
        public int seed;
        public static Random obj;
        // Default Constructor
        public aRandomVariable()
        {
            seed = 999;
            obj = new Random(seed);
        }
        /// <summary>
        /// Default Constructor with seed
        /// </summary>
        /// <param name="seed"> Takes a user inputted seed </param>
        public aRandomVariable(int seed)
        {
            obj = new Random(seed);
        }
        /// <summary>
        /// Returns a random number generated by the random number generator.
        /// </summary>
        /// <returns>Returns an Integer between 1 and 6 inclusive</returns>
        public int getRand(int max)
        {
            return obj.Next(0,max);
            
        }
        /// <summary>
        /// "Reseeds" the random object with a user 
        /// inputted seed in form TextbOX
        /// </summary>
        /// <param name="seed"></param>
        public void setSeed(int seed)
        {
            obj = new Random(seed);
        }

    }
}
